# Generated by Django 5.0.4 on 2024-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_is_sold_alter_houses_forsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
